### ISSUE TITLE
Error when trying to train with low_resource=True

### ISSUE THREAD

**Issue by sergiotasconmorales** [wang-zhanyu/R2GenGPT#1]
Hello, 
Thank you for sharing your code. I'm trying to run `train_shallow.sh` on two RTX3090 (24 GB of memory each) with `low_resource=True`, but I keep getting the attached output with an error about the location of some layers. I think the problem is that the mapping of the model is done automatically by `Accelerate`, but then some related layers are in different devices. I've tried many things to solve the issue, without success. If you know what could be causing the issue, I would appreciate any information that could point me in the right direction. Thanks

> CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
{'accelerator': 'gpu',
 'accumulate_grad_batches': 1,
 'annotation': './data/mimic_cxr/annotation.json',
 'base_dir': '/storage/workspaces/artorg_aimi/ws_00000/sergio/radrep/mimic-cxr-jpg-google/files',
 'batch_size': 8,
 'beam_size': 3,
 'ckpt_file': None,
 'dataset': 'mimic_cxr',
 'delta_file': None,
 'devices': 2,
 'diversity_penalty': 0,
 'do_sample': False,
 'end_sym': '</s>',
 'every_n_train_steps': 0,
 'freeze_vm': True,
 'global_only': False,
 'gradient_clip_val': 1,
 'learning_rate': 0.0001,
 'length_penalty': 2.0,
 'limit_test_batches': 1.0,
 'limit_train_batches': 1.0,
 'limit_val_batches': 0.5,
 'llama_model': 'meta-llama/Llama-2-7b-chat-hf',
 'llm_alpha': 16,
 'llm_r': 16,
 'llm_use_lora': False,
 'lora_dropout': 0.1,
 'low_resource': True,
 'max_epochs': 5,
 'max_length': 100,
 'max_new_tokens': 120,
 'min_new_tokens': 80,
 'no_repeat_ngram_size': 2,
 'num_beam_groups': 1,
 'num_nodes': 1,
 'num_sanity_val_steps': 2,
 'num_workers': 8,
 'precision': '16',
 'prefetch_factor': 4,
 'repetition_penalty': 2.0,
 'savedmodel_path': './save/mimic_cxr/v1_shallow',
 'scorer_types': ['Bleu_4', 'CIDEr'],
 'strategy': 'ddp',
 'temperature': 0,
 'test': False,
 'test_batch_size': 16,
 'val_batch_size': 12,
 'val_check_interval': 0.5,
 'validate': False,
 'vis_alpha': 16,
 'vis_r': 16,
 'vis_use_lora': False,
 'vision_model': 'microsoft/swin-base-patch4-window7-224',
 'weights': [0.5, 0.5]}
[rank: 0] Global seed set to 42
/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/fabric/connector.py:554: UserWarning: 16 is supported for historical reasons but its usage is discouraged. Please set your precision to 16-mixed instead!
  rank_zero_warn(
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Loading vision encoder:microsoft/swin-base-patch4-window7-224
Some weights of the model checkpoint at microsoft/swin-base-patch4-window7-224 were not used when initializing SwinModel: ['classifier.bias', 'classifier.weight']
> - This IS expected if you are initializing SwinModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing SwinModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading Frozen vision encoder:microsoft/swin-base-patch4-window7-224 -- Done
Loading LLAMA

>Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:03<00:03,  3.50s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:04<00:00,  2.18s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:04<00:00,  2.38s/it]
Loading LLAMA Done
[rank: 0] Global seed set to 42
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
>distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

>You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

>  | Name           | Type             | Params
----------------------------------------------------
>0 | visual_encoder | SwinModel        | 86.7 M
1 | llama_model    | LlamaForCausalLM | 6.7 B 
2 | embed_tokens   | Embedding        | 131 M 
3 | llama_proj     | Linear           | 4.2 M 
4 | layer_norm     | LayerNorm        | 8.2 K 
----------------------------------------------------
>4.2 M     Trainable params
6.8 B     Non-trainable params
6.8 B     Total params
27,317.462Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.

>Sanity Checking: 0it [00:00, ?it/s]
Sanity Checking:   0%|          | 0/2 [00:00<?, ?it/s]
Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/bitsandbytes/autograd/_functions.py:318: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Traceback (most recent call last):
  File "/storage/homefs/st20f757/vqa/ReportWizard/train.py", line 59, in <module>
    main()
  File "/storage/homefs/st20f757/vqa/ReportWizard/train.py", line 55, in main
    train(args)
  File "/storage/homefs/st20f757/vqa/ReportWizard/train.py", line 47, in train
    trainer.fit(model, datamodule=dm)
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 41, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 91, in launch
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1014, in _run_stage
    self._run_sanity_check()
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1043, in _run_sanity_check
    val_loop.run()
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 375, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 291, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/strategies/ddp.py", line 336, in validation_step
    return self.model(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/lightning/pytorch/overrides/base.py", line 102, in forward
    return self._forward_module.validation_step(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/vqa/ReportWizard/models/R2GenGPT.py", line 249, in validation_step
    outputs = self.llama_model.generate(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/transformers/generation/utils.py", line 1611, in generate
    return self.beam_search(
           ^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/transformers/generation/utils.py", line 2909, in beam_search
    outputs = self(
              ^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states = self.input_layernorm(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/st20f757/.conda/envs/rw/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 88, in forward
    return (self.weight * hidden_states).to(input_dtype)
            ~~~~~~~~~~~~^~~~~~~~~~~~~~~
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

**Comment by sergiotasconmorales** [comment]
If anyone runs into this issue, check out my fork of this repo, which runs on smaller GPUs. Adding autocast in the validation step method seems to have solved the issue.
