### ISSUE TITLE
question

### ISSUE THREAD

**Issue by shenshaowei** [wang-zhanyu/R2GenGPT#15]
hi,When I finish training the first epoch, I encounter a **BrokenPipeError: [Errno 32] Broken pipe** at the end of the **validation DataLoader**. I've read online that setting **--num_workers 0** can help, but I get an error when I do that. How can I resolve this?

````
Epoch 0: 100%|█████████▉| 201/202 [03:31<00:01,  1.05s/it, v_num=0, loss=1.940]loss: tensor(2.1493, device='cuda:0', grad_fn=<NllLossBackward0>)
Epoch 0: 100%|██████████| 202//data108/user_hzx/SSW/R2GenGPT/dataset/data_helper1.py:72: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  images = [torch.tensor(img) for img in images]  # 如果是 numpy.ndarray
/data108/user_hzx/SSW/R2GenGPT/dataset/data_helper1.py:72: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  images = [torch.tensor(img) for img in images]  # 如果是 numpy.ndarray
/data108/user_hzx/SSW/R2GenGPT/dataset/data_helper1.py:72: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  images = [torch.tensor(img) for img in images]  # 如果是 numpy.ndarray
/data108/user_hzx/SSW/R2GenGPT/dataset/data_helper1.py:72: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  images = [torch.tensor(img) for img in images]  # 如果是 numpy.ndarray
/data108/user_hzx/SSW/R2GenGPT/dataset/data_helper1.py:72: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  images = [torch.tensor(img) for img in images]  # 如果是 numpy.ndarray
/data108/user_hzx/SSW/R2GenGPT/dataset/data_helper1.py:72: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  images = [torch.tensor(img) for img in images]  # 如果是 numpy.ndarray
/data108/user_hzx/SSW/R2GenGPT/dataset/data_helper1.py:72: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  images = [torch.tensor(img) for img in images]  # 如果是 numpy.ndarray
/data108/user_hzx/SSW/R2GenGPT/dataset/data_helper1.py:72: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  images = [torch.tensor(img) for img in images]  # 如果是 numpy.ndarray
                                                                        Traceback (most recent call last):alidation DataLoader 0: 100%|██████████| 34/34 [11:22<00:00, 20.07s/it]
  File "/data108/user_hzx/SSW/R2GenGPT/train.py", line 56, in <module>
    main()
  File "/data108/user_hzx/SSW/R2GenGPT/train.py", line 53, in main
    train(args)
  File "/data108/user_hzx/SSW/R2GenGPT/train.py", line 45, in train
    trainer.fit(model, datamodule=dm)
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1016, in _run_stage
    self.fit_loop.run()
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 134, in run
    self.on_advance_end()
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 248, in on_advance_end
    self.val_loop.run()
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 122, in run
    return self.on_run_end()
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 244, in on_run_end
    self._on_evaluation_epoch_end()
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 326, in _on_evaluation_epoch_end
    call._call_lightning_module_hook(trainer, hook_name)
  File "/data108/user_hzx/anaconda3/envs/r2/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 144, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/data108/user_hzx/SSW/R2GenGPT/models/R2GenGPT.py", line 287, in on_validation_epoch_end
    eval_res = self.score(ref=ref,hypo=hypo)
  File "/data108/user_hzx/SSW/R2GenGPT/models/R2GenGPT.py", line 107, in score
    score, scores = scorer.compute_score(ref, hypo)
  File "/data108/user_hzx/SSW/R2GenGPT/evalcap/meteor/meteor.py", line 77, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/data108/user_hzx/SSW/R2GenGPT/evalcap/meteor/meteor.py", line 108, in _stat
    self.meteor_p.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
Epoch 0: 100%|██████████| 202/202 [15:06<00:00,  4.49s/it, v_num=0, loss=2.150]
```

**Comment by Mda233** [comment]
I am facing the same error. Any solution for this?

**Comment by Mda233** [comment]
I think the issue happens because of the meteor metrics function. I started the training by commenting https://github.com/wang-zhanyu/R2GenGPT/blob/main/models/R2GenGPT.py#L101
`#            (Meteor(), "METEOR"),`
